(() => {
  const STORE = "lumi_community_posts_v1";
  const user = window.SanaAuth?.currentUser?.() || { username: "guest", nickname: "You" };
  const seed = [
    { id:"music-1", author:"User 1", username:"user1", avatar:"./image/avatar.jpg", category:"music", text:"This song always brightens my mood whenever I listen to it. Highly recommend!", likes:30, createdAt:Date.now()-7200000, comments:[] },
    { id:"johnny-1", author:"Johnny Xu", username:"johnny", avatar:"./image/johnny-profile.jpg", category:"life", text:"The recent study pressure has been quite intense, but swimming always helps me unwind quickly and recharge my energy.", image:"./image/johnny.png", likes:45, createdAt:Date.now()-10800000, comments:[{author:"Maya", text:"Swimming is such a good reset.", createdAt:Date.now()-9000000}] }
  ];
  const state = { filter:"all", sort:"latest", query:"", commentPost:null, image:null };
  const getPosts = () => { try { const saved=JSON.parse(localStorage.getItem(STORE)); return Array.isArray(saved) ? saved : seed; } catch { return seed; } };
  const savePosts = posts => localStorage.setItem(STORE, JSON.stringify(posts));
  const esc = value => String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
  const ago = time => { const mins=Math.max(1,Math.floor((Date.now()-time)/60000)); return mins<60 ? `${mins} min ago` : mins<1440 ? `${Math.floor(mins/60)} hours ago` : `${Math.floor(mins/1440)} days ago`; };
  const liked = post => (post.likedBy || []).includes(user.username);
  function visiblePosts() { return getPosts().filter(post => (state.filter==="all"||post.category===state.filter) && `${post.author} ${post.text}`.toLowerCase().includes(state.query)).filter(post => state.sort!=="following" || post.username===user.username).sort((a,b)=>state.sort==="popular" ? b.likes-a.likes : b.createdAt-a.createdAt); }
  function render() { const posts=visiblePosts(); document.getElementById("postList").innerHTML=posts.length ? posts.map(post => `<article class="community-post" data-id="${post.id}"><header><img src="${post.avatar}" alt="${esc(post.author)}" class="post-avatar"><div><h2>${esc(post.author)} <small>${ago(post.createdAt)}</small></h2><p>${esc(post.text)}</p>${post.image?`<img src="${post.image}" class="activity-image" alt="Post attachment">`:""}</div><button class="more-button" aria-label="More options">•••</button></header><footer><button class="like-button ${liked(post)?"liked":""}" data-action="like" aria-pressed="${liked(post)}"><svg viewBox="0 0 24 24"><path d="M12 21s-7-4.6-7-10a4 4 0 0 1 7-2.7A4 4 0 0 1 19 11c0 5.4-7 10-7 10Z"/></svg><span>${post.likes}</span></button><button data-action="comment">◯ Comment <span class="comment-count">${post.comments?.length||0}</span></button><button data-action="save">▱ Save</button></footer>${post.comments?.length?`<div class="post-comments">${post.comments.slice(-2).map(c=>`<p><b>${esc(c.author)}</b> ${esc(c.text)}</p>`).join("")}</div>`:""}</article>`).join("") : `<p class="empty-feed">No posts here yet. Share the first one.</p>`; }
  function update(id, fn) { const posts=getPosts(); const post=posts.find(x=>x.id===id); if (!post) return; fn(post); savePosts(posts); render(); }
  document.getElementById("newPostButton").onclick=()=>document.getElementById("shareModal").hidden=false;
  document.querySelectorAll("[data-close]").forEach(btn=>btn.onclick=()=>document.getElementById(btn.dataset.close).hidden=true);
  document.querySelectorAll(".share-modal").forEach(modal=>modal.onclick=e=>{ if(e.target===modal) modal.hidden=true; });
  document.getElementById("shareImage").onchange=e=>{ const file=e.target.files[0]; if(!file)return; if(file.size>2_000_000){alert("Please choose an image under 2 MB.");e.target.value="";return;} const reader=new FileReader(); reader.onload=()=>{state.image=reader.result;const preview=document.getElementById("imagePreview");preview.src=state.image;preview.hidden=false}; reader.readAsDataURL(file); };
  document.getElementById("shareForm").onsubmit=e=>{ e.preventDefault(); const posts=getPosts(); posts.push({id:`post-${Date.now()}`,author:user.nickname||user.username,username:user.username,avatar:"./image/lego.png",category:document.getElementById("shareType").value,text:document.getElementById("shareInput").value.trim(),image:state.image||undefined,likes:0,likedBy:[],comments:[],createdAt:Date.now()}); savePosts(posts); state.image=null; e.target.reset();document.getElementById("imagePreview").hidden=true;document.getElementById("shareModal").hidden=true;state.sort="latest";document.querySelectorAll(".feed-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.sort==="latest"));render(); };
  document.querySelectorAll(".community-categories button").forEach(btn=>btn.onclick=()=>{state.filter=btn.dataset.filter;document.querySelectorAll(".community-categories button").forEach(b=>b.classList.toggle("active",b===btn));render();});
  document.querySelectorAll(".feed-tabs button").forEach(btn=>btn.onclick=()=>{state.sort=btn.dataset.sort;document.querySelectorAll(".feed-tabs button").forEach(b=>b.classList.toggle("active",b===btn));render();});
  document.getElementById("postSearch").oninput=e=>{state.query=e.target.value.toLowerCase();render();};
  document.getElementById("postList").onclick=e=>{ const button=e.target.closest("button[data-action]"); if(!button)return; const id=e.target.closest(".community-post").dataset.id; if(button.dataset.action==="like") update(id,p=>{p.likedBy=p.likedBy||[];const i=p.likedBy.indexOf(user.username);if(i>=0){p.likedBy.splice(i,1);p.likes=Math.max(0,p.likes-1)}else{p.likedBy.push(user.username);p.likes++}}); if(button.dataset.action==="comment"){state.commentPost=id; openComments();} if(button.dataset.action==="save"){button.classList.toggle("saved");button.textContent=button.classList.contains("saved")?"✓ Saved":"▱ Save";} };
  function openComments(){const post=getPosts().find(p=>p.id===state.commentPost);document.getElementById("commentList").innerHTML=(post.comments||[]).map(c=>`<p><b>${esc(c.author)}</b><span>${esc(c.text)}</span></p>`).join("")||"<p class='empty-comments'>Be the first to leave a kind reply.</p>";document.getElementById("commentModal").hidden=false;}
  document.getElementById("commentForm").onsubmit=e=>{e.preventDefault();const text=document.getElementById("commentInput").value.trim();if(!text)return;update(state.commentPost,p=>{p.comments=p.comments||[];p.comments.push({author:user.nickname||user.username,text,createdAt:Date.now()})});document.getElementById("commentInput").value="";openComments();};
  render();
})();
